site_name: Module 01
site_description: Computational Thinking met Python
site_author: Jack Henze

# Aanpassen als het naar de ONC github repo gaat
site_url: https://jhenze-dev.github.io/module01/

theme:
  name: material
  language: nl
  custom_dir: overrides

  features:
    # - navigation.instant
    - navigation.tracking
    - toc.follow
    #- toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link

plugins:
  - search
  - macros:
      module_name: main
      include_yaml:
        - schedule: docs/data/schedule.yml
        - resources_catalog: docs/data/general-resources.yml

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes

  - toc:
      permalink: false

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.snippets:
      base_path:
        - docs
      check_paths: true

  - pymdownx.arithmatex:
      generic: true

  - pymdownx.details

  - pymdownx.highlight:
      anchor_linenums: true

  - pymdownx.inlinehilite

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.keys

  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  # Basis
  - assets/css/style.css
  - assets/css/navigation.css

  # Componenten
  - assets/css/reference.css
  - assets/css/goals.css
  - assets/css/test.css
  - assets/css/badges.css
  - assets/css/details.css
  - assets/css/video.css
  - assets/css/mermaid.css

  # Paginatypes
  - assets/css/homepage.css
  - assets/css/week.css
  - assets/css/tset.css
  - assets/css/pset-index.css
  - assets/css/pset.css
  - assets/css/understanding.css
  
extra_javascript:
  - assets/js/page-toc.js
  - https://unpkg.com/mermaid@11/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  language: !ENV [LANGUAGE, nl]